version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - app/.env
    networks:
      - mongodb_network
    deploy:
      resources:
        limits:
          cpus: '3.2'
          memory: 3000M
    ports:
      - "3333:8000"

networks:
  mongodb_network:
    external: true

