version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - mongodb_network
#    deploy:
#      resources:
#        limits:
#          cpus: '8.0'
#          memory: 1400M
    ports:
      - "3333:8000"

networks:
  mongodb_network:
    external: true